pivot_mode = "always"
prompt = "build-string (build-string (ansi cu) (do -i {whoami} | str trim) '@' ( do -i {hostname} | str trim) (ansi reset) ' ' ) (ansi gb) (pwd) (ansi reset) '(' (ansi cb) (do -i { git rev-parse --abbrev-ref HEAD } | str trim ) (ansi reset) ')-' (ansi yb) (date format '%m/%d/%Y %H:%M') (char newline)  (ansi reset) (ansi rb) '>>=' (ansi reset) ' '  "
skip_welcome_message = true

#startup commands
startup = [
    "alias lsd = ls -ds", 
    "source /home/user/.config/nu/sources/source.nu"
]

table_mode = "light"

# Extra environment variables
[env]
EDITOR = "micro"

# line edditor settings
[line_editor]
completion_match_method = "case-insensitive"
completion_type = "circular"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"

#settings for bat
[textview]
paging_mode = "quitifonescreen"
wrapping_mode = "nowrapping"
