path = [
    "/home/user/.local/bin", 
    "/usr/local/bin", 
    "/usr/bin", 
    "/usr/local/sbin", 
    "/usr/bin/site_perl", 
    "/usr/bin/vendor_perl", 
    "/usr/bin/core_perl", 
    "/opt/android-ndk", 
    "/opt/android-sdk/platform-tools", 
    "/opt/android-sdk/tools", 
    "/opt/android-sdk/tools/bin", 
    "/var/lib/flatpak/exports/bin", 
    "/usr/lib/jvm/default/bin"
]

pivot_mode = "always"
prompt = "build-string (build-string (ansi cu) (do -i {whoami} | str trim) '@' ( do -i {hostname} | str trim) (ansi reset) ' ' ) (ansi gd) (pwd) (ansi reset) '(' (ansi cb) (do -i { git rev-parse --abbrev-ref HEAD } | str trim ) (ansi reset) ')-' (ansi yd) (date format '%m/%d/%Y %H:%M') (char newline)  (ansi reset) (ansi rb) '>>=' (ansi reset) ' '  "
skip_welcome_message = true
startup = [
    "alias lsd = ls -ds", 
    "alias ll = {ls -lds|select name type mode group size accessed}",
    "alias la = ls -a",
    "alias lla = ls -la",
    "alias grep = grep --color=auto",
    "alias kittyimg = kitty +kitten icat",
    "alias probeKit = /home/user/Projects/myprojects/probeKit/interpreter.py",
    "alias bashe = bash -c",
    "alias javashell = /usr/lib/jvm/default/bin/jshell",
    "alias nfind = find",
    "alias find = ^find",
    "source /home/user/.config/nu/sources/source.nu"
]
table_mode = "light"

[env]
EDITOR = "vim"

[color_config]
separator_color = "bd"
header_align = "l"
header_color = "ub"
index_color = "rb"
primitive_binary = "cb"

[line_editor]
completion_match_method = "case-insensitive"
completion_type = "circular"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"

[textview]
pager = "less"
wrapping_mode = "nowrapping"
